#!/usr/bin/env elixir
File.read!(System.argv() |> hd)
|> String.trim()
|> String.split("\n")
|> Enum.map(&String.split(&1, "   "))
|> Enum.map(fn nums -> Enum.map(nums, &String.to_integer/1) end)
|> List.zip()
|> Enum.map(&Tuple.to_list/1)
|> Enum.map(&Enum.sort/1)
|> List.zip()
|> Enum.map(&Tuple.to_list/1)
|> Enum.map(fn [a, b] -> abs(abs(a) - abs(b)) end)
|> Enum.sum()
|> IO.inspect()
